# 2. Write programs in Python using NumPy library to do the following:
## a. Compute the mean, standard deviation, and variance of a two dimensional random integer array along the second axis.

In [4]:
import numpy as np
arr=np.random.randint(20,80,(5,3))
arr

array([[52, 62, 41],
       [52, 74, 39],
       [27, 45, 61],
       [38, 20, 31],
       [27, 64, 28]])

In [15]:
print("MEAN along second axis")
np.mean(arr,axis=1)

MEAN along second axis


array([51.66666667, 55.        , 44.33333333, 29.66666667, 39.66666667])

In [17]:
print("STANDARD DEVIATION along second axis")
np.std(arr,axis=1)

STANDARD DEVIATION along second axis


array([ 8.57645355, 14.44529912, 13.88844444,  7.40870359, 17.21110752])

In [18]:
np.var(arr,axis=1)

array([ 73.55555556, 208.66666667, 192.88888889,  54.88888889,
       296.22222222])

## b. Get the indices of the sorted elements of a given array.
## a. B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]

In [26]:
arr=np.array([56,48,22,41,78,91,24,46,8,33])
arr

array([56, 48, 22, 41, 78, 91, 24, 46,  8, 33])

In [28]:
index=arr.argsort()

In [31]:
print("Indices of sorted elements of an array")
index

Indices of sorted elements of an array


array([8, 2, 6, 9, 3, 7, 1, 0, 4, 5], dtype=int64)

In [32]:
arr[index]

array([ 8, 22, 24, 33, 41, 46, 48, 56, 78, 91])

## c. Create a 2-dimensional array of size m x n integer elements, also print the shape, type and data type of the array and then reshape it into nx m array, n and m are user inputs given at the run time.

# Input of m and n

In [40]:
m=int(input("Enter the number of rows: "))
n=int(input("Enter the number of columns: "))

Enter the number of rows: 4
Enter the number of columns: 3


In [42]:
arr=np.random.randint(10,50,(m,n))
arr

array([[12, 44, 36],
       [26, 16, 42],
       [11, 47, 27],
       [27, 47, 37]])

# Shape of an array

In [44]:
arr.shape

(4, 3)

# Type of an array

In [48]:
type(arr)

numpy.ndarray

# Data Type of an array

In [45]:
arr.dtype

dtype('int32')

# Reshape an array

In [49]:
arr1=arr.reshape(n,m)

In [50]:
arr1

array([[12, 44, 36, 26],
       [16, 42, 11, 47],
       [27, 27, 47, 37]])

# Transpose of an array

In [52]:
arr.T

array([[12, 26, 11, 27],
       [44, 16, 47, 47],
       [36, 42, 27, 37]])

## d. Test whether the elements of a given array are zero, non-zero and NaN. Record the indices of these elements in three separate arrays.

In [82]:
arr=np.array([1,0,1,1,0,None,1,0,0,1,1,5,8,4,0,None,1,0,0,14,None])
arr

array([1, 0, 1, 1, 0, None, 1, 0, 0, 1, 1, 5, 8, 4, 0, None, 1, 0, 0, 14,
       None], dtype=object)

In [83]:
print("NONZERO INDEX")
nonzero=np.where(arr!=0)
nonzero

NONZERO INDEX


(array([ 0,  2,  3,  5,  6,  9, 10, 11, 12, 13, 15, 16, 19, 20],
       dtype=int64),)

In [84]:
print("Non zero elements")
arr[nonzero]

Non zero elements


array([1, 1, 1, None, 1, 1, 1, 5, 8, 4, None, 1, 14, None], dtype=object)

In [85]:
print("ZERO INDEX")
zero=np.where(arr==0)
zero

ZERO INDEX


(array([ 1,  4,  7,  8, 14, 17, 18], dtype=int64),)

In [86]:
print("Zero elements")
arr[zero]

Zero elements


array([0, 0, 0, 0, 0, 0, 0], dtype=object)

In [87]:
print("NAN INDEX")
no=np.where(arr==None)
no

NAN INDEX


(array([ 5, 15, 20], dtype=int64),)

In [88]:
print("NAN elements")
arr[no]

NAN elements


array([None, None, None], dtype=object)